# syntax=docker/dockerfile:1

FROM golang:1.17-alpine

COPY bin/notifier ./notifier

ENV NOTIFIER_INTERVAL=50ms
ENV NOTIFIER_MAXALLOWEDERRORS=5
ENV NOTIFIER_HTTPREQUESTTIMEOUT=1s
ENV NOTIFIER_LOGLEVEL=debug
ENV NOTIFIER_BUFFERSIZE=30
ENV NOTIFIER_MAXIDLECONNS=50
ENV NOTIFIER_MAXIDLECONNSPERHOST=50

ENTRYPOINT [ "./notifier" ]
